---
title: "flat_database.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# get_database_path

```{r function-get_database_path}
#' get_database_path
#'
#' @noRd
#' @rdname fct_comics_db
get_database_path <- function() {
  Sys.getenv(
    "COMICS_SQL_PATH",
    unset = ""
  )
}
```

```{r examples-get_database_path}
get_database_path()
```

```{r tests-get_database_path}
test_that("get_database_path works", {
  expect_equal(
    withr::with_envvar(
      c("COMICS_SQL_PATH" = "BOBI"),
      {
        get_database_path()
      }
    ),
    "BOBI"
  )
})
```

# connect_to_comics_db

```{r function-connect_to_comics_db}
#' Connection
#'
#' @noRd
#' @rdname fct_comics_db
connect_to_comics_db <- function() {
  DBI::dbConnect(
    RSQLite::SQLite(),
    get_database_path()
  )
}
```

```{r example-connect_to_comics_db}
connect_to_comics_db()
```

```{r tests-connect_to_comics_db}
test_that("connect_to_comics_db works", {
  expect_true(inherits(connect_to_comics_db(), "SQLiteConnection"))
})
```

# read/write/update

```{r function-read}
#' Comics db functions
#'
#' @rdname fct_comics_db

init_comics_db <- function() {
  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  if (!"comics" %in% DBI::dbListTables(con)) {
    DBI::dbCreateTable(
      con,
      "comics",
      fields = c(
        id_db = "TEXT",
        id_document = "TEXT",
        ISBN = "TEXT",
        auteur = "TEXT",
        possede = "INTEGER",
        titre = "TEXT",
        annee_publication = "TEXT",
        nb_pages = "INTEGER",
        editeur = "TEXT",
        note = "INTEGER",
        type_publication = "TEXT",
        statut = "TEXT",
        lien_cover = "TEXT",
        datetime = "TEXT"
      )
    )
  }

  read_comics_db()
}


#' @rdname fct_comics_db

read_comics_db <- function() {
  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  DBI::dbReadTable(con, "comics")
}
#' @rdname fct_comics_db

append_comics_db <- function(
  ISBN,
  auteur,
  titre,
  possede,
  annee_publication,
  nb_pages,
  editeur,
  note,
  type_publication,
  statut,
  lien_cover
) {
  datetime <- Sys.time()

  id_db <- digest::digest(
    c(
      ISBN,
      auteur,
      titre,
      possede,
      annee_publication,
      nb_pages,
      editeur,
      note,
      type_publication,
      statut,
      lien_cover,
      datetime
    )
  )
  id_document <- paste0(
    "doc_",
    digest::digest(as.character(ISBN))
  )

  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  DBI::dbAppendTable(
    con,
    "comics",
    data.frame(
      id_db = id_db,
      id_document = id_document,
      ISBN = ISBN,
      auteur = auteur,
      titre = titre,
      possede = possede,
      annee_publication = annee_publication,
      nb_pages = nb_pages,
      editeur = editeur,
      note = note,
      type_publication = type_publication,
      statut = statut,
      lien_cover = lien_cover,
      datetime = datetime
    )
  )
}
#' @rdname fct_comics_db

delete_comics_db <- function() {
  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  DBI::dbRemoveTable(
    con,
    "comics"
  )
}
```

```{r example-read}
withr::with_tempdir({
  withr::with_envvar(
    c("COMICS_SQL_PATH" = "BOBI.sqlite"),
    {
      init_comics_db()
      read_comics_db()
      append_comics_db(
        ISBN = "1234567890",
        auteur = "BILL",
        titre = "BOBI",
        possede = 1,
        annee_publication = "2020-01-01",
        nb_pages = 154,
        editeur = "truc",
        note = 5,
        type_publication = "comics",
        statut = "Lu",
        lien_cover = "https://mycover.com"
      )
      read_comics_db()
      delete_comics_db()
      unlink("BOBI.sqlite")
    }
  )
})
```

```{r tests-read}
test_that("init/read/append works", {
  withr::with_tempdir({
    withr::with_envvar(
      c("COMICS_SQL_PATH" = "BOBI.sqlite"),
      {
        init_comics_db()
        expect_true(inherits(read_comics_db(), "data.frame"))
        expect_equal(
          init_comics_db(),
          read_comics_db()
        )

        expect_equal(
          append_comics_db(
            ISBN = "1234567890",
            auteur = "BILL",
            titre = "BOBI",
            possede = 1,
            annee_publication = "2020-01-01",
            nb_pages = 154,
            editeur = "truc",
            note = 5,
            type_publication = "comics",
            statut = "Lu",
            lien_cover = "https://mycover.com"
          ),
          1
        )

        db <- read_comics_db()

        expect_equal(
          db$ISBN,
          "1234567890"
        )

        expect_equal(
          db$auteur,
          "BILL"
        )

        expect_equal(
          db$titre,
          "BOBI"
        )

        expect_equal(
          db$possede,
          1
        )

        expect_equal(
          db$annee_publication,
          "2020-01-01"
        )

        expect_equal(
          db$nb_pages,
          154
        )

        expect_equal(
          db$editeur,
          "truc"
        )

        expect_equal(
          db$note,
          5
        )

        expect_equal(
          db$type_publication,
          "comics"
        )

        expect_equal(
          db$statut,
          "Lu"
        )

        expect_equal(
          db$lien_cover,
          "https://mycover.com"
        )
      }
    )
  })
})
```

# get_most_recent_entry_per_doc
    
```{r function-get_most_recent_entry_per_doc}
#' Get most recent entry per document
#' @param db comics db
#' @return A data.frame with the most recent entry per document
#' @importFrom dplyr group_by slice_max ungroup
#' @rdname fct_comics_db
#' @noRd
get_most_recent_entry_per_doc <- function(db) {
  db |>
    group_by(id_document) |>
    slice_max(datetime) |>
    ungroup()
}
```
  
  
```{r tests-get_most_recent_entry_per_doc}
test_that("get_most_recent_entry_per_doc works", {
  withr::with_tempdir({
    withr::with_envvar(
      c("COMICS_SQL_PATH" = "BOBI.sqlite"),
      {
        init_comics_db()

        # Document 1
        append_comics_db(
          ISBN = "1234567890",
          auteur = "BILL",
          titre = "BOBI",
          possede = 0,
          annee_publication = "2020-01-01",
          nb_pages = 154,
          editeur = "truc",
          note = 5,
          type_publication = "comics",
          statut = "Non-lu",
          lien_cover = "https://mycover.com"
        )

        db <- read_comics_db()
        res <- get_most_recent_entry_per_doc(db)

        expect_equal(
          res |>
            dplyr::filter(ISBN == "1234567890") |>
            dplyr::pull(statut),
          "Non-lu"
        )

        expect_equal(
          res |>
            dplyr::filter(ISBN == "1234567890") |>
            dplyr::pull(possede),
          0
        )

        append_comics_db(
          ISBN = "1234567890",
          auteur = "BILL",
          titre = "BOBI",
          possede = 1,
          annee_publication = "2020-01-01",
          nb_pages = 154,
          editeur = "truc",
          note = 5,
          type_publication = "comics",
          statut = "Non-lu",
          lien_cover = "https://mycover.com"
        )

        db <- read_comics_db()
        res <- get_most_recent_entry_per_doc(db)


        expect_equal(
          res |>
            dplyr::filter(ISBN == "1234567890") |>
            dplyr::pull(statut),
          "Non-lu"
        )

        expect_equal(
          res |>
            dplyr::filter(ISBN == "1234567890") |>
            dplyr::pull(possede),
          1
        )

        append_comics_db(
          ISBN = "1234567890",
          auteur = "BILL",
          titre = "BOBI",
          possede = 1,
          annee_publication = "2020-01-01",
          nb_pages = 154,
          editeur = "truc",
          note = 5,
          type_publication = "comics",
          statut = "Lu",
          lien_cover = "https://mycover.com"
        )


        db <- read_comics_db()
        res <- get_most_recent_entry_per_doc(db)

        expect_equal(
          res |>
            dplyr::filter(ISBN == "1234567890") |>
            dplyr::pull(statut),
          "Lu"
        )

        expect_equal(
          res |>
            dplyr::filter(ISBN == "1234567890") |>
            dplyr::pull(possede),
          1
        )

        # Document 2
        append_comics_db(
          ISBN = "9786543210",
          auteur = "BILL",
          titre = "BOBI2",
          possede = 1,
          annee_publication = "2020-01-01",
          nb_pages = 154,
          editeur = "truc",
          note = 5,
          type_publication = "comics",
          statut = "Non-lu",
          lien_cover = "https://mycover.com"
        )

        db <- read_comics_db()
        res <- get_most_recent_entry_per_doc(db)

        expect_equal(
          res |>
            dplyr::filter(ISBN == "9786543210") |>
            dplyr::pull(statut),
          "Non-lu"
        )

        expect_equal(
          res |>
            dplyr::filter(ISBN == "9786543210") |>
            dplyr::pull(possede),
          1
        )

        append_comics_db(
          ISBN = "9786543210",
          auteur = "BILL",
          titre = "BOBI2",
          possede = 1,
          annee_publication = "2020-01-01",
          nb_pages = 154,
          editeur = "truc",
          note = 5,
          type_publication = "comics",
          statut = "Lu",
          lien_cover = "https://mycover.com"
        )

        db <- read_comics_db()
        res <- get_most_recent_entry_per_doc(db)

        expect_equal(
          res |>
            dplyr::filter(ISBN == "9786543210") |>
            dplyr::pull(statut),
          "Lu"
        )

        expect_equal(
          res |>
            dplyr::filter(ISBN == "9786543210") |>
            dplyr::pull(possede),
          1
        )
      }
    )
  })
  unlink("BOBI.sqlite")
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_database.Rmd",
  vignette_name = NA,
  check = FALSE
)
```

 