---
title: "flat_webcam.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# clean_data_url
    
```{r function-clean_data_url}
#' Clean data URL from webcam
#' @param dataURL A string with the data URL
#' @return A string with the data URL without the prefix
#' @rdname fct_webcam
#' @noRd
clean_data_url <- function(dataurl) {
  gsub(
    pattern = "data:image/jpeg;base64,",
    replacement = "",
    x = dataurl
  )
}
```

```{r tests-clean_data_url}
test_that("clean_data_url works", {
  dataurl <- "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD"
  expect_equal(
    clean_data_url(dataurl = dataurl),
    "/9j/4AAQSkZJRgABAQAAAQABAAD"
  )
})
```
  
# export_img_from_dataurl
    
```{r function-export_img_from_dataurl}
#' Export image from data URL
#' @param dataurl A string with the data URL
#' @param output_img A string with the path to the output image
#' @return write an img in inst/
#' @importFrom base64enc base64decode
#' @rdname fct_webcam
#' @export
export_img_from_dataurl <- function(
  dataurl,
  output_img
) {
  cleaned_url <- clean_data_url(dataurl)

  url_as_text <- tempfile(pattern = "base64", fileext = ".txt")
  file.create(url_as_text)
  writeLines(cleaned_url, url_as_text)
  inconn <- file(url_as_text, "rb")
  outconn <- file(output_img, "wb")
  base64decode(what = inconn, output = outconn)
  close(inconn)
  close(outconn)
  unlink(url_as_text)
}
```
  
  
```{r tests-export_img_from_dataurl}
test_that("export_img_from_dataurl works", {
  dataurl <- readLines(
    file.path(
      system.file(package = "mycomicslibrary"),
      "unit_test",
      "base64url.txt"
    )
  )
  img_out <- tempfile(fileext = ".jpg")

  export_img_from_dataurl(
    dataurl = dataurl,
    output_img = img_out
  )
  expect_true(
    file.exists(img_out)
  )
  expect_true(
    file.size(img_out) > 0
  )
  unlink(img_out)
})
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_webcam.Rmd",
  vignette_name = NA,
  check = FALSE
)
```

 