---
title: "flat_additional.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# show_hide_ids_depending_on_db_size
    
```{r function-show_hide_ids_depending_on_db_size}
#' show or hide elements depending on the size of a database
#'
#' @return side effect
#' @rdname fct_mod300_400
#' @noRd
show_hide_ids_depending_on_db_size <- function(db, table_id, nobook_id) {
  if (
    !isTruthy(db) ||
      nrow(db) == 0
  ) {
    golem::invoke_js(
      "showid",
      nobook_id
    )
    golem::invoke_js(
      "hideid",
      table_id
    )
  } else {
    golem::invoke_js(
      "hideid",
      nobook_id
    )
    golem::invoke_js(
      "showid",
      table_id
    )
  }
}
```

# call_sweet_alert_depending_on_db_append
    
```{r function-call_sweet_alert_depending_on_db_append}
#' call sweet alert depending on the result of an append operation

#' @return side effect
#' @rdname fct_mod300_400
#' @noRd
call_sweet_alert_depending_on_db_append <- function(append_res, msg_success, msg_error) {
  if (append_res == 1) {
    golem::invoke_js(
      "call_sweetalert2",
      message = list(
        type = "success",
        msg = msg_success
      )
    )
  } else {
    golem::invoke_js(
      "call_sweetalert2",
      message = list(
        type = "error",
        msg = msg_error
      )
    )
  }
}
```
  

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_mod300_400.Rmd",
  vignette_name = NA,
  check = FALSE
)
```

