---
title: "flat_full.Rmd for working package"
output: html_document
editor_options: 
  chunk_output_type: console
---

<!-- Run this 'development' chunk -->
<!-- Store every call to library() that you need to explore your functions -->

```{r development, include=FALSE}
library(testthat)
```

<!--
 You need to run the 'description' chunk in the '0-dev_history.Rmd' file before continuing your code there.

If it is the first time you use {fusen}, after 'description', you can directly run the last chunk of the present file with inflate() inside.
--> 

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
library(httr2)
library(jsonlite)
library(tidyjson)
library(glue)
library(cli)
library(janitor)
library(tidyselect)
library(purrr)
library(dplyr)
# a recuperer à partir des resultats de la requete
cover_url <- glue::glue("http://covers.openlibrary.org/b/isbn/1931498717-M.jpg")
```

# call_open_library_api
    
```{r function-call_open_library_api}
#' Appel à l'API Open Library
#' @param root_api l'URL de base de l'API
#' @param isbn_number le numéro ISBN 10
#' @return un tibble avec les informations de l'API
#' @importFrom cli cli_alert_warning
#' @importFrom glue glue
#' @importFrom httr2 request req_perform resp_body_json
#' @importFrom tidyjson spread_all
#' @export
#' @rdname fct_open_library
call_open_library_api <- function(
  root_api = "https://openlibrary.org/api/books",
  isbn_number
) {
  if (isFALSE(as.character(isbn_number))) {
    stop("Le numéro ISBN doit être passé sous forme de chaine de caractères")
  }

  url <- glue("{root_api}?bibkeys=ISBN:{isbn_number}&jscmd=details&format=json")

  req <- request(url)

  result <- try(
    req |>
      req_perform() |>
      resp_body_json() |>
      spread_all(),
    silent = TRUE
  )

  return(result)
}
```
  
```{r example-call_open_library_api}
call_open_library_api(isbn_number = "2365772013")
```
  
```{r tests-call_open_library_api}
skip_if_offline()

test_that("call_open_library_api works", {
  isbn_number <- "2365772013"

  result <- call_open_library_api(isbn_number = isbn_number)

  expect_equal(
    result,
    structure(
      list(
        document.id = 1L,
        bib_key = "ISBN:2365772013",
        info_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
        preview = "noview",
        preview_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
        thumbnail_url = "https://covers.openlibrary.org/b/id/10867159-S.jpg",
        details.title = "SAGA - Tome 1",
        details.publish_date = "Mar 14, 2013",
        details.number_of_pages = 168,
        details.physical_format = "paperback",
        details.key = "/books/OL32230088M",
        details.latest_revision = 1,
        details.revision = 1,
        details.type.key = "/type/edition",
        details.notes.type = "/type/text",
        details.notes.value = "Source title: SAGA - Tome 1 (URBAN INDIES) (French Edition)",
        details.created.type = "/type/datetime",
        details.created.value = "2021-04-22T18:16:16.598948",
        details.last_modified.type = "/type/datetime",
        details.last_modified.value = "2021-04-22T18:16:16.598948",
        ..JSON = list(`ISBN:2365772013` = list(
          bib_key = "ISBN:2365772013",
          info_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
          preview = "noview",
          preview_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
          thumbnail_url = "https://covers.openlibrary.org/b/id/10867159-S.jpg",
          details = list(
            type = list(key = "/type/edition"),
            title = "SAGA - Tome 1",
            authors = list(
              list(
                key = "/authors/OL9159259A",
                name = "Brian K. Vaughan"
              ),
              list(
                key = "/authors/OL9159260A",
                name = "Fiona Staples"
              )
            ),
            publish_date = "Mar 14, 2013",
            source_records = list("amazon:2365772013"),
            number_of_pages = 168L,
            publishers = list("URBAN COMICS"),
            isbn_10 = list(
              "2365772013"
            ),
            isbn_13 = list("9782365772013"),
            physical_format = "paperback",
            notes = list(
              type = "/type/text",
              value = "Source title: SAGA - Tome 1 (URBAN INDIES) (French Edition)"
            ),
            covers = list(10867159L),
            works = list(list(key = "/works/OL24344304W")),
            key = "/books/OL32230088M",
            latest_revision = 1L,
            revision = 1L,
            created = list(
              type = "/type/datetime",
              value = "2021-04-22T18:16:16.598948"
            ),
            last_modified = list(
              type = "/type/datetime",
              value = "2021-04-22T18:16:16.598948"
            )
          )
        ))
      ),
      row.names = 1L,
      class = c(
        "tbl_json",
        "tbl_df",
        "tbl",
        "data.frame"
      )
    )
  )

  # No result with a wrong isbn_number
  result <- call_open_library_api(isbn_number = "XXXX")

  expect_equal(
    nrow(result),
    0
  )

  # Error 404
  result <- call_open_library_api(
    root_api = "https://openlibrary.org/api/bouks",
    isbn_number = "2365772013"
  )

  expect_true(
    inherits(result, "try-error")
  )

  # Error 500
  result <- call_open_library_api(
    root_api = "https://bobi.com/api/books",
    isbn_number = "2365772013"
  )

  expect_true(
    inherits(result, "try-error")
  )
})
```  

# clean_open_library_result
    
```{r function-clean_open_library_result}
#' Nettoyage du résultat de l'API Open Library
#' @param book_tibble a tibble with the result of the API call
#' @return a tibble with the cleaned result of the API call
#' @importFrom janitor clean_names
#' @importFrom dplyr select mutate
#' @importFrom tidyselect everything any_of
#' @importFrom purrr map map_chr possibly
#' @export
#' @rdname fct_open_library
#' @examples
#' isbn_number <- "2365772013"
#' result <- call_open_library_api(isbn_number = isbn_number)
#'
#' clean_open_library_result(result)
clean_open_library_result <- function(book_tibble) {
  book_tibble_cleaned_names <- book_tibble |>
    clean_names()

  df_part <- book_tibble_cleaned_names |>
    as.data.frame() |>
    select(
      any_of(
        c(
          "info_url",
          "thumbnail_url",
          "details_title",
          "details_publish_date",
          "details_number_of_pages"
        )
      )
    )

  json <- book_tibble_cleaned_names$json

  possibly_get_authors <- possibly(get_authors, otherwise = NA_character_)
  possibly_get_isbn10 <- possibly(get_isbn10, otherwise = NA_character_)
  possibly_get_isbn13 <- possibly(get_isbn13, otherwise = NA_character_)
  possibly_get_publishers <- possibly(get_publishers, otherwise = NA_character_)
  possibly_get_date <- possibly(clean_date, otherwise = NA_character_)
  author <- possibly_get_authors(json)
  isbn_10 <- possibly_get_isbn10(json)
  isbn_13 <- possibly_get_isbn13(json)
  publisher <- possibly_get_publishers(json)


  df_part <- df_part |>
    mutate(
      author = author,
      isbn_10 = isbn_10,
      isbn_13 = isbn_13,
      publisher = publisher,
      details_publish_date = possibly_get_date(details_publish_date)
    )

  colnames(df_part) <- gsub("details_", "", colnames(df_part))

  df_part |>
    select(
      title,
      author,
      everything()
    )
}

#' @noRd
get_nested_field <- function(json, field) {
  json |>
    purrr::map(~ .x$details) |>
    purrr::map(~ .x[[field]]) |>
    purrr::map(
      ~ .x |>
        purrr::map_chr(~ .x[[1]])
    ) |>
    purrr::map_chr(~ paste(.x, collapse = ", "))
}

#' @noRd
get_authors <- function(json) {
  json |>
    purrr::map(~ .x$details) |>
    purrr::map(~ .x[["authors"]]) |>
    purrr::map(
      ~ .x |>
        purrr::map_chr(~ .x$name)
    ) |>
    purrr::map_chr(~ paste(.x, collapse = ", "))
}

#' @noRd
get_isbn10 <- function(json) {
  get_nested_field(json, "isbn_10")
}

#' @noRd
get_isbn13 <- function(json) {
  get_nested_field(json, "isbn_13")
}

#' @noRd
get_publishers <- function(json) {
  get_nested_field(json, "publishers")
}

#' @noRd
clean_date <- function(date) {
  regmatches(date, regexec("\\d{4,4}", date))[[1]]
}
```
  
```{r example-clean_open_library_result}
isbn_number <- "2365772013"
result <- call_open_library_api(isbn_number = isbn_number)

clean_open_library_result(result)
```
  
```{r tests-clean_open_library_result}
test_that("clean_open_library_result works", {
  isbn_number <- "2365772013"
  result <- call_open_library_api(isbn_number = isbn_number) |>
    clean_open_library_result()

  expect_equal(
    result,
    structure(
      list(
        title = "SAGA - Tome 1",
        author = c(`ISBN:2365772013` = "Brian K. Vaughan, Fiona Staples"),
        info_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
        thumbnail_url = "https://covers.openlibrary.org/b/id/10867159-S.jpg",
        publish_date = "2013",
        number_of_pages = 168,
        isbn_10 = c(`ISBN:2365772013` = "2365772013"),
        isbn_13 = c(`ISBN:2365772013` = "9782365772013"),
        publisher = c(`ISBN:2365772013` = "URBAN COMICS")
      ),
      row.names = c(
        NA,
        -1L
      ),
      class = "data.frame"
    )
  )
})
```
 
# get_cover
    
```{r function-get_cover}
#' Get the cover of a book from Open Library
#' @param root_api the base URL of the API
#' @param isbn_number the ISBN 10 number or the ISBN 13 number of the book
#' @param cover_size the size of the cover
#' @param resourcepath the path to the resource
#' @return a URL to the cover of the book
#' @importFrom glue glue
#' @importFrom utils download.file
#' @rdname fct_open_library
#' @export
#' @examples
#' get_cover(isbn_number = "9782365772013")
#' path <- "home/yohann/Documents/perso/mycomicslibrary/inst/app/www/cover_tmp/9782365772013.jpg"
get_cover <- function(
  root_api = "http://covers.openlibrary.org/b/isbn",
  isbn_number,
  cover_size = "M",
  resourcepath = resourcePaths()["covers"]
) {
  match.arg(cover_size, c("S", "M", "L"))
  url <- glue("{root_api}/{isbn_number}-{cover_size}.jpg")
  cover_output <- file.path(
    resourcepath,
    paste0(isbn_number, ".jpg")
  )

  if (!file.exists(cover_output)) {
    cover_dl <- try(
      download.file(
        url = url,
        cover_output,
        mode = "wb"
      ),
      silent = TRUE
    )

    if (inherits(cover_dl, "try-error")) {
      cover_output <- file.path(
        resourcepath,
        "image-not-found.jpg"
      )
    }
  }
  return(
    cover_output
  )
}
```
  
```{r example-get_cover}
get_cover(isbn_number = "9782365772013")
path <- "home/yohann/Documents/perso/mycomicslibrary/inst/app/www/cover_tmp/9782365772013.jpg"
```
  
```{r tests-get_cover}
skip_if_offline()
test_that("get_cover works", {
  list.files(
    app_sys(
      "app",
      "www",
      "cover_tmp"
    ),
    full.names = TRUE,
    pattern = "\\d{13}\\.jpg$"
  ) |>
    file.remove()

  cover_path <- get_cover(isbn_number = "9782365772013")

  expect_true(
    file.exists(cover_path)
  )

  expect_equal(
    cover_path,
    file.path(
      app_sys(
        "app",
        "www",
        "cover_tmp"
      ),
      "9782365772013.jpg"
    )
  )
  unlink(cover_path)
})
```
  

# give_me_one_random_isbn
    
```{r function-give_me_one_random_isbn}
#' Return a random ISBN from mycomicslibrary::isbn_sample
#' @return a random ISBN
#' @rdname fct_open_library
#' @export
give_me_one_random_isbn <- function() {
  mycomicslibrary::isbn_sample |>
    sample(1) |>
    as.character()
}
```
  
```{r example-give_me_one_random_isbn}
give_me_one_random_isbn()
```
  
```{r tests-give_me_one_random_isbn}
test_that("give_me_one_random_isbn works", {
  isbn_number <- give_me_one_random_isbn()

  expect_true(
    is.character(isbn_number)
  )

  expect_equal(
    nchar(isbn_number),
    13
  )

  expect_equal(
    regmatches(isbn_number, regexec("^[0-9]{13}$", isbn_number))[[1]],
    isbn_number
  )
})
```
  


```{r development-inflate, eval=FALSE}
# Keep eval=FALSE to avoid infinite loop in case you hit the knit button
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_open_library.Rmd",
  vignette_name = NA,
  check = FALSE
)
```
