---
title: "flat_additional.Rmd empty"
output: html_document
editor_options: 
  chunk_output_type: console
---

```{r development, include=FALSE}
library(testthat)
```

```{r development-load}
# Load already included functions if relevant
pkgload::load_all(export_all = FALSE)
```

# showSpinner
    
```{r function-showSpinner}
#' Show spinner
#'
#' @param inputId spinner div id
#' @return side effect. show spinner
#' @rdname fct_spinner
#' @noRd
showSpinner <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
) {
  session$sendCustomMessage("show_spinner", inputId)
}
```

  
# hideSpinner
    
```{r function-hideSpinner}
#' Hide spinner
#'
#' @param inputId spinner div id
#' @param session session
#' @return side effect. Hide le spinner
#' @rdname fct_spinner
#' @noRd
hideSpinner <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
) {
  session$sendCustomMessage("hide_spinner", inputId)
}
```


# withSpinner

```{r function-withSpinner}
#' withSpinner
#' @param expr L'opération a réaliser.
#' @param session session shiny
#' @return html
#' @rdname fct_spinner
#' @noRd
withSpinner <- function(
  expr,
  session = shiny::getDefaultReactiveDomain()
) {
  showSpinner(inputId = "lds-ring", session = session)
  force(expr)
  on.exit(hideSpinner(inputId = "lds-ring", session = session))
}
```

```{r development-inflate, eval=FALSE}
# Run but keep eval=FALSE to avoid infinite loop
# Execute in the console directly
fusen::inflate(
  flat_file = "dev/flat_spinner.Rmd",
  vignette_name = NA,
  check = FALSE
)
```

