# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

test_that("shiny_alert_isbn_detected_on_img works", {
  expect_true(inherits(shiny_alert_isbn_detected_on_img, "function"))
})

test_that("shiny_alert_isbn_not_detected_on_img works", {
  expect_true(inherits(shiny_alert_isbn_not_detected_on_img, "function"))
})
