# WARNING - Generated by {fusen} from dev/flat_webcam.Rmd: do not edit by hand

test_that("clean_data_url works", {
  dataurl <- "data:image/jpeg;base64,/9j/4AAQSkZJRgABAQAAAQABAAD"
  expect_equal(
    clean_data_url(dataurl = dataurl),
    "/9j/4AAQSkZJRgABAQAAAQABAAD"
  )
})
