# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

test_that("prepare_comics_db_to_see_wishlist works", {
  expect_true(inherits(prepare_comics_db_to_see_wishlist, "function"))
})
