# WARNING - Generated by {fusen} from dev/flat_webcam_utils.Rmd: do not edit by hand

test_that("take_picture_from_webcam_ui works", {
  expect_true(
    inherits(
      take_picture_from_webcam_ui(id = "bobi"),
      "shiny.tag.list"
    )
  )
})
