# WARNING - Generated by {fusen} from dev/flat_webcam.Rmd: do not edit by hand

test_that("export_img_from_dataurl works", {
  dataurl <- readLines(
    file.path(
      system.file(package = "mycomicslibrary"),
      "unit_test",
      "base64url.txt"
    )
  )
  img_out <- tempfile(fileext = ".jpg")

  export_img_from_dataurl(
    dataurl = dataurl,
    output_img = img_out
  )
  expect_true(
    file.exists(img_out)
  )
  expect_true(
    file.size(img_out) > 0
  )
  unlink(img_out)
})
