# WARNING - Generated by {fusen} from dev/flat_open_library.Rmd: do not edit by hand

test_that("call_open_library_api works", {
  skip_if_offline()

  isbn10 <- "2365772013"

  result <- call_open_library_api(isbn10 = isbn10)

  expect_equal(
    result,
    structure(
      list(
        document.id = 1L,
        bib_key = "ISBN:2365772013",
        info_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
        preview = "noview",
        preview_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
        thumbnail_url = "https://covers.openlibrary.org/b/id/10867159-S.jpg",
        details.title = "SAGA - Tome 1",
        details.publish_date = "Mar 14, 2013",
        details.number_of_pages = 168,
        details.physical_format = "paperback",
        details.key = "/books/OL32230088M",
        details.latest_revision = 1,
        details.revision = 1,
        details.type.key = "/type/edition",
        details.notes.type = "/type/text",
        details.notes.value = "Source title: SAGA - Tome 1 (URBAN INDIES) (French Edition)",
        details.created.type = "/type/datetime",
        details.created.value = "2021-04-22T18:16:16.598948",
        details.last_modified.type = "/type/datetime",
        details.last_modified.value = "2021-04-22T18:16:16.598948",
        ..JSON = list(`ISBN:2365772013` = list(
          bib_key = "ISBN:2365772013",
          info_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
          preview = "noview",
          preview_url = "https://openlibrary.org/books/OL32230088M/SAGA_-_Tome_1",
          thumbnail_url = "https://covers.openlibrary.org/b/id/10867159-S.jpg",
          details = list(
            type = list(key = "/type/edition"),
            title = "SAGA - Tome 1",
            authors = list(
              list(
                key = "/authors/OL9159259A",
                name = "Brian K. Vaughan"
              ),
              list(
                key = "/authors/OL9159260A",
                name = "Fiona Staples"
              )
            ),
            publish_date = "Mar 14, 2013",
            source_records = list("amazon:2365772013"),
            number_of_pages = 168L,
            publishers = list("URBAN COMICS"),
            isbn_10 = list(
              "2365772013"
            ),
            isbn_13 = list("9782365772013"),
            physical_format = "paperback",
            notes = list(
              type = "/type/text",
              value = "Source title: SAGA - Tome 1 (URBAN INDIES) (French Edition)"
            ),
            covers = list(10867159L),
            works = list(list(key = "/works/OL24344304W")),
            key = "/books/OL32230088M",
            latest_revision = 1L,
            revision = 1L,
            created = list(
              type = "/type/datetime",
              value = "2021-04-22T18:16:16.598948"
            ),
            last_modified = list(
              type = "/type/datetime",
              value = "2021-04-22T18:16:16.598948"
            )
          )
        ))
      ),
      row.names = 1L,
      class = c(
        "tbl_json",
        "tbl_df",
        "tbl",
        "data.frame"
      )
    )
  )

  # No result with a wrong isbn10
  result <- call_open_library_api(isbn10 = "XXXX")

  expect_equal(
    nrow(result),
    0
  )

  # Error 404
  result <- call_open_library_api(
    root_api = "https://openlibrary.org/api/bouks",
    isbn10 = "2365772013"
  )

  expect_equal(
    result,
    "erreur 404"
  )

  # Error 500
  result <- call_open_library_api(
    root_api = "https://bobi.com/api/books",
    isbn10 = "2365772013"
  )
  expect_equal(
    result,
    "le serveur ne répond pas"
  )
})
