# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

test_that("make_stars_rating_div works", {
  stars <- make_stars_rating_div(note = 0)

  expect_true(
    length(regmatches(x = stars, m = gregexpr("checked", stars))[[1]]) == 0
  )

  stars <- make_stars_rating_div(note = 1) |> as.character()
  expect_true(
    length(regmatches(x = stars, m = gregexpr("checked", stars))[[1]]) == 1
  )

  stars <- make_stars_rating_div(note = 5) |> as.character()
  expect_true(
    length(regmatches(x = stars, m = gregexpr("checked", stars))[[1]]) == 5
  )
})
