# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

test_that("create_html_for_modal_modify_book_in_collection works", {
  expect_true(inherits(create_html_for_modal_modify_book_in_collection, "function"))
})
