# WARNING - Generated by {fusen} from dev/flat_open_library.Rmd: do not edit by hand

test_that("get_cover works", {
  expect_equal(
    get_cover(isbn_number = "9782365772013"),
    "http://covers.openlibrary.org/b/isbn/9782365772013-M.jpg"
  )

  expect_equal(
    get_cover(isbn_number = "9782365772013", cover_size = "S"),
    "http://covers.openlibrary.org/b/isbn/9782365772013-S.jpg"
  )
})
