# WARNING - Generated by {fusen} from dev/flat_open_library.Rmd: do not edit by hand

#' Appel à l'API Open Library
#' @param root_api l'URL de base de l'API
#' @param isbn_number le numéro ISBN 10
#' @return un tibble avec les informations de l'API
#' @importFrom cli cli_alert_warning
#' @importFrom glue glue
#' @importFrom httr2 request req_perform resp_body_json
#' @importFrom tidyjson spread_all
#' @export
#' @examples
#' call_open_library_api(isbn_number = "2365772013")
call_open_library_api <- function(
  root_api = "https://openlibrary.org/api/books",
  isbn_number
) {
  if (isFALSE(as.character(isbn_number))) {
    stop("Le numéro ISBN doit être passé sous forme de chaine de caractères")
  }

  url <- glue("{root_api}?bibkeys=ISBN:{isbn_number}&jscmd=details&format=json")

  req <- request(url)

  result <- try(
    req |>
      req_perform() |>
      resp_body_json() |>
      spread_all(),
    silent = TRUE
  )

  return(result)
}
