# WARNING - Generated by {fusen} from dev/flat_open_library.Rmd: do not edit by hand

#' Appel à l'API Open Library
#' @param root_api l'URL de base de l'API
#' @param isbn10 le numéro ISBN 10
#' @return un tibble avec les informations de l'API
#' @importFrom cli cli_alert_warning
#' @importFrom glue glue
#' @importFrom httr2 request req_perform resp_body_json
#' @importFrom tidyjson spread_all
#' @export
#' @examples
#' call_open_library_api(isbn10 = "2365772013")
call_open_library_api <- function(
  root_api = "https://openlibrary.org/api/books",
  isbn10
) {
  if (isFALSE(as.character(isbn10))) {
    stop("Le numéro ISBN 10 doit être passé sous forme de chaine de caractères")
  }

  url <- glue("{root_api}?bibkeys=ISBN:{isbn10}&jscmd=details&format=json")

  req <- request(url)

  return(
    try(
      req |>
        req_perform() |>
        resp_body_json() |>
        spread_all()
    )
  )
}
