# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' HTML for modal modify book in collection
#'
#' @return a div with the HTML for the modal to modify a book in the collection
#' @param current_book the current book
#' @param ns the namespace
#' @importFrom shiny tags sliderInput textInput selectInput
#' @export
create_html_for_modal_modify_book_in_collection <- function(
  current_book,
  ns
) {
  tagList(
    tags$div(
      id = ns("modal_modify_book_in_collection"),
      style = "
          display: flex;
          flex-direction: column;
          ",
      tags$div(
        tags$ul(
          style = "text-align: left; list-style-type: none;",
          textInput(
            inputId = ns("annee_publication"),
            label = "Année de publication",
            value = current_book$annee_publication
          ),
          textInput(
            inputId = ns("nb_pages"),
            label = "Nombre de pages",
            value = current_book$nb_pages
          ),
          textInput(
            inputId = ns("auteur"),
            label = "Auteur(s)",
            value = current_book$auteur
          ),
          textInput(
            inputId = ns("editeur"),
            label = "Editeur(s)",
            value = current_book$editeur
          ),
          selectInput(
            inputId = ns("note"),
            label = "Note",
            choices = 0:5,
            selected = current_book$note
          ),
          selectInput(
            inputId = ns("format"),
            label = "Format",
            choices = c("BD", "Comics", "Roman graphique", "Autre", "A définir"),
            selected = current_book$type_publication
          ),
          selectInput(
            inputId = ns("etat"),
            label = "Etat",
            choices = c("A lire", "En cours", "Lu", "A définir"),
            selected = current_book$statut
          )
        )
      )
    )
  )
}
