# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' Title
#'
#' Description
#'
#' @return
#'
#' @export
#' @examples
#' create_html_for_modal_modify_book_in_collection()
create_html_for_modal_modify_book_in_collection <- function(
  ns) {
  tagList(
    tags$div(
      id = ns("modal_modify_book_in_collection"),
      style = "
          display: flex;
          flex-direction: column;
          ",
      tags$div(
        tags$ul(
          style = "text-align: left; list-style-type: none;",
          selectInput(
            inputId = ns("note"),
            label = "Note",
            choices = 0:5
          ),
          selectInput(
            inputId = ns("format"),
            label = "Format",
            choices = c("BD", "Comics", "Roman graphique", "Autre")
          ),
          selectInput(
            inputId = ns("etat"),
            label = "Etat",
            choices = c("A lire", "En cours", "Lu")
          )
        )
      )
    )
  )
}
