# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' Extract n stars from selectinput
#' @param selectinput_result the result of a selectinput
#' @return the number of stars checked
#'
#' @export
extract_nstars_from_selectinput <- function(selectinput_result) {
  length(
    regmatches(
      x = selectinput_result,
      m = gregexpr(
        "checked",
        selectinput_result
      )
    )[[1]]
  )
}
