# WARNING - Generated by {fusen} from dev/flat_additional.Rmd: do not edit by hand

#' @noRd
#' @param detected_isbn_value The detected ISBN value
#' @importFrom shinyalert shinyalert
#' @importFrom shiny tags tagAppendChild
#' @rdname fct_mod_120
#' @examples
#' shiny_alert_isbn_detected_on_img()
shiny_alert_isbn_detected_on_img <- function(detected_isbn_value) {
  #  voir gestion des ns
  shinyalert(
    html = TRUE,
    title = "ISBN détecté !",
    type = "success",
    showCancelButton = FALSE,
    showConfirmButton = FALSE,
    text = tagList(
      tags$div(
        style = "
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;",
        tags$h5(
          sprintf("ISBN détecté : %s", detected_isbn_value)
        ),
        tags$span(
          tags$button(
            id = "validate_detected_isbn",
            class = "btn btn-success",
            "Ajouter l'ISBN détecté au menu de recherche",
            onclick =
              sprintf(
                "Shiny.setInputValue('add_detected_isbn_to_collection', %s)",
                paste0('\\"detected_isbn_value\\"')
              )
          ),
          tags$button(
            id = "leave_modal",
            style = "background-color: #d9534f; border-color: #d43f3a;",
            "Abandonner"
          )
        )
      )
    )
  )
}

#' @noRd
#' @rdname fct_mod_120
#' @importFrom shinyalert shinyalert
#' @importFrom shiny tags
#' @examples
#' shiny_alert_isbn_not_detected_on_img()
shiny_alert_isbn_not_detected_on_img <- function() {

}
