# WARNING - Generated by {fusen} from dev/flat_mod500.Rmd: do not edit by hand

#' @noRd
#' @rdname fct_mod500
get_var_to_display_on_chartjs <- function() {
  list(
    "Année de publication" = "annee_publication",
    "Note" = "note",
    "Etat" = "statut",
    "Format" = "type_publication"
  )
}
