# WARNING - Generated by {fusen} from dev/flat_webcam_utils.Rmd: do not edit by hand

#' Generate a UI for taking a picture from the webcam
#'
#' @return a shiny tagList
#' @importFrom shiny tagList tags
#' @rdname fct_webcam_utils
#' @export
take_picture_from_webcam_ui <- function(id) {
  tagList(
    tags$div(
      id = id,
      style = "display: none;",
      tags$div(
        class = "camera",
        tags$video(id = "video", "Video stream not available"),
        tags$button(id = "startbutton", "Take photo")
      ),
      tags$canvas(id = "canvas"),
      tags$div(
        class = "output",
        tags$img(
          id = "photo",
          alt = "The screen capture will appear in this box."
        )
      )
    )
  )
}
