# WARNING - Generated by {fusen} from dev/flat_spinner.Rmd: do not edit by hand

#' Show spinner
#'
#' @param inputId spinner div id
#' @return side effect. show spinner
#' @rdname fct_spinner
#' @noRd
showSpinner <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
) {
  session$sendCustomMessage("show_spinner", inputId)
}

#' Hide spinner
#'
#' @param inputId spinner div id
#' @param session session
#' @return side effect. Hide le spinner
#' @rdname fct_spinner
#' @noRd
hideSpinner <- function(
  inputId,
  session = shiny::getDefaultReactiveDomain()
) {
  session$sendCustomMessage("hide_spinner", inputId)
}

#' withSpinner
#' @param expr L'opération a réaliser.
#' @param session session shiny
#' @return html
#' @rdname fct_spinner
#' @noRd
withSpinner <- function(
  expr,
  session = shiny::getDefaultReactiveDomain()
) {
  showSpinner(inputId = "lds-ring", session = session)
  force(expr)
  on.exit(hideSpinner(inputId = "lds-ring", session = session))
}
