# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' Make stars rating div
#' @param note a note between 0 and max_note
#' @param max_note the maximum note
#' @return a div with stars
#' @importFrom htmltools tags
#' @rdname fct_mod_130
#' @export
#' @examples
#' make_stars_rating_div(note = 1)
make_stars_rating_div <- function(
  note,
  max_note = 5
) {
  stars_full <- stars_empty <- list()
  if (note != 0) {
    stars_full <- lapply(1:note, function(x) {
      tags$span(class = "fa fa-star checked")
    })
  }

  if (note != max_note) {
    stars_empty <- lapply(1:(max_note - note), function(x) {
      tags$span(class = "fa fa-star")
    })
  }

  tagList(
    c(stars_full, stars_empty)
  ) |> as.character()
}

#' Prepare comics database to see collection
#' @param comics_db a comics database
#' @param ns the namespace
#' @return a comics database with only the columns needed to see the collection
#' @rdname fct_mod_130
#' @importFrom dplyr select mutate
#' @importFrom purrr map_chr
#' @importFrom shiny selectInput
#' @export
prepare_comics_db_to_see_collection <- function(comics_db, ns) {
  db <- comics_db |>
    select(
      id_document,
      titre,
      annee_publication,
      nb_pages,
      auteur,
      editeur,
      note,
      type_publication,
      statut,
      lien_cover,
      ISBN
    ) |>
    mutate(
      note = map_chr(note, make_stars_rating_div)
    )

  modify_properties_buttons <- sapply(seq_len(nrow(db)), function(i) {
    sprintf(
      '<button type="button" class="btn btn-primary" id="%s" onclick="%s">Modifier</button>',
      ns(paste0("modify_book_button", i)),
      sprintf(
        "Shiny.setInputValue(
        '%s',
        '%s',
        {priority : 'event'}
      );
      Shiny.setInputValue(
        '%s',
        Math.random(),
        {priority : 'event'}
      );",
        ns("document_to_modify_id"),
        db$id_document[i],
        ns("modify_button_clicked")
      )
    )
  })

  delete_book_buttons <- sapply(seq_len(nrow(db)), function(i) {
    sprintf(
      '<button type="button" class="btn btn-danger" id="%s" onclick="%s">Supprimer</button>',
      ns(paste0("delete_book_button", i)),
      sprintf(
        "Shiny.setInputValue(
        '%s',
        '%s',
        {priority : 'event'}
      );
      Shiny.setInputValue(
        '%s',
        Math.random(),
        {priority : 'event'}
      );",
        ns("document_to_delete_id"),
        db$id_document[i],
        ns("delete_button_clicked")
      )
    )
  })

  db$modify_properties_buttons <- modify_properties_buttons
  db$delete_book_buttons <- delete_book_buttons

  db |>
    select(-id_document)
}
