# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' Prepare comics database to see collection
#' @return a comics database with only the columns needed to see the collection
#' @rdname fct_mod_130
#' @importFrom dplyr select mutate
#' @export
prepare_comics_db_to_see_collection <- function(comics_db) {
  db <- comics_db |>
    select(
      titre,
      date_publication,
      nb_pages,
      editeur,
      possede,
      note,
      type_publication,
      statut,
      lien_cover,
      ISBN
    ) #|>
  # mutate(
  #   lien_cover = paste0(
  #     "<a href='",
  #     lien_cover,
  #     "' target=\"_blank\">",
  #     "Couverture",
  #     "</a>"
  #   )
  # )
  # (cell) => gridjs.html(`${cell}`)
}
