# WARNING - Generated by {fusen} from dev/flat_open_library.Rmd: do not edit by hand

#' Appel à l'API Open Library
#' @param root_api l'URL de base de l'API
#' @param isbn_number le numéro ISBN 10
#' @return un tibble avec les informations de l'API
#' @importFrom cli cli_alert_warning
#' @importFrom glue glue
#' @importFrom httr2 request req_perform resp_body_json
#' @importFrom tidyjson spread_all
#' @export
#' @rdname fct_open_library
#' @examples
#' call_open_library_api(isbn_number = "2365772013")
call_open_library_api <- function(
  root_api = "https://openlibrary.org/api/books",
  isbn_number
) {
  if (isFALSE(as.character(isbn_number))) {
    stop("Le numéro ISBN doit être passé sous forme de chaine de caractères")
  }

  url <- glue("{root_api}?bibkeys=ISBN:{isbn_number}&jscmd=details&format=json")

  req <- request(url)

  result <- try(
    req |>
      req_perform() |>
      resp_body_json() |>
      spread_all(),
    silent = TRUE
  )

  return(result)
}

#' Nettoyage du résultat de l'API Open Library
#' @param book_tibble a tibble with the result of the API call
#' @return a tibble with the cleaned result of the API call
#' @importFrom janitor clean_names
#' @importFrom dplyr select mutate
#' @importFrom tidyselect everything any_of
#' @importFrom purrr map map_chr
#' @export
#' @rdname fct_open_library
#' @examples
#' isbn_number <- "2365772013"
#' result <- call_open_library_api(isbn_number = isbn_number)
#'
#' clean_open_library_result(result)
clean_open_library_result <- function(book_tibble) {
  book_tibble_cleaned_names <- book_tibble |>
    clean_names()

  df_part <- book_tibble_cleaned_names |>
    as.data.frame() |>
    select(
      any_of(
        c(
          "info_url",
          "thumbnail_url",
          "details_title",
          "details_publish_date",
          "details_number_of_pages"
        )
      )
    )

  json <- book_tibble_cleaned_names$json

  author <- get_authors(json)
  isbn_10 <- get_isbn10(json)
  isbn_13 <- get_isbn13(json)
  publisher <- get_publishers(json)


  df_part <- df_part |>
    mutate(
      author = author,
      isbn_10 = isbn_10,
      isbn_13 = isbn_13,
      publisher = publisher,
      details_publish_date = regmatches(details_publish_date, regexec("\\d{4,4}", details_publish_date))[[1]]
    )

  colnames(df_part) <- gsub("details_", "", colnames(df_part))

  df_part |>
    select(
      title,
      author,
      everything()
    )
}

#' @noRd
get_nested_field <- function(json, field) {
  json |>
    purrr::map(~ .x$details) |>
    purrr::map(~ .x[[field]]) |>
    purrr::map(
      ~ .x |>
        purrr::map_chr(~ .x[[1]])
    ) |>
    purrr::map_chr(~ paste(.x, collapse = ", "))
}

#' @noRd
get_authors <- function(json) {
  json |>
    purrr::map(~ .x$details) |>
    purrr::map(~ .x[["authors"]]) |>
    purrr::map(
      ~ .x |>
        purrr::map_chr(~ .x$name)
    ) |>
    purrr::map_chr(~ paste(.x, collapse = ", "))
}

#' @noRd
get_isbn10 <- function(json) {
  get_nested_field(json, "isbn_10")
}

#' @noRd
get_isbn13 <- function(json) {
  get_nested_field(json, "isbn_13")
}

#' @noRd
get_publishers <- function(json) {
  get_nested_field(json, "publishers")
}

#' Get the cover of a book from Open Library
#' @param root_api the base URL of the API
#' @param isbn_number the ISBN 10 number or the ISBN 13 number of the book
#' @param cover_size the size of the cover
#' @return a URL to the cover of the book
#' @importFrom glue glue
#' @rdname fct_open_library
#' @export
#' @examples
#' get_cover(isbn_number = "9782365772013")
get_cover <- function(
  root_api = "http://covers.openlibrary.org/b/isbn",
  isbn_number,
  cover_size = "M"
) {
  match.arg(cover_size, c("S", "M", "L"))
  glue("{root_api}/{isbn_number}-{cover_size}.jpg")
}

#' Return a random ISBN from mycomicslibrary::isbn_sample
#' @return a random ISBN
#' @rdname fct_open_library
#' @export
#' @examples
#' give_me_one_random_isbn()
give_me_one_random_isbn <- function() {
  mycomicslibrary::isbn_sample |>
    sample(1) |>
    as.character()
}
