# WARNING - Generated by {fusen} from dev/flat_webcam.Rmd: do not edit by hand

#' Clean data URL from webcam
#' @param dataURL A string with the data URL
#' @return A string with the data URL without the prefix
#' @rdname fct_webcam
#' @noRd
clean_data_url <- function(dataurl) {
  gsub(
    pattern = "data:image/jpeg;base64,",
    replacement = "",
    x = dataurl
  )
}
