# WARNING - Generated by {fusen} from dev/flat_open_library.Rmd: do not edit by hand

#' Appel à l'API Open Library
#' @param root_api l'URL de base de l'API
#' @param isbn_number le numéro ISBN 10
#' @return un tibble avec les informations de l'API
#' @importFrom cli cli_alert_warning
#' @importFrom glue glue
#' @importFrom httr2 request req_perform resp_body_json
#' @importFrom tidyjson spread_all
#' @export
#' @rdname fct_open_library
#' @examples
#' call_open_library_api(isbn_number = "2365772013")
call_open_library_api <- function(
  root_api = "https://openlibrary.org/api/books",
  isbn_number
) {
  if (isFALSE(as.character(isbn_number))) {
    stop("Le numéro ISBN doit être passé sous forme de chaine de caractères")
  }

  url <- glue("{root_api}?bibkeys=ISBN:{isbn_number}&jscmd=details&format=json")

  req <- request(url)

  result <- try(
    req |>
      req_perform() |>
      resp_body_json() |>
      spread_all(),
    silent = TRUE
  )

  return(result)
}

#' Nettoyage du résultat de l'API Open Library
#' @param book_tibble a tibble with the result of the API call
#' @return a tibble with the cleaned result of the API call
#' @importFrom janitor clean_names
#' @importFrom dplyr select mutate
#' @importFrom tidyselect everything any_of
#' @importFrom purrr map map_chr possibly
#' @export
#' @rdname fct_open_library
#' @examples
#' isbn_number <- "2365772013"
#' result <- call_open_library_api(isbn_number = isbn_number)
#'
#' clean_open_library_result(result)
#' isbn_number <- "2365772013"
#' result <- call_open_library_api(isbn_number = isbn_number)
#'
#' clean_open_library_result(result)
clean_open_library_result <- function(book_tibble) {
  book_tibble_cleaned_names <- book_tibble |>
    clean_names()

  df_part <- book_tibble_cleaned_names |>
    as.data.frame() |>
    select(
      any_of(
        c(
          "info_url",
          "thumbnail_url",
          "details_title",
          "details_publish_date",
          "details_number_of_pages"
        )
      )
    )

  json <- book_tibble_cleaned_names$json

  possibly_get_authors <- possibly(get_authors, otherwise = NA_character_)
  possibly_get_isbn10 <- possibly(get_isbn10, otherwise = NA_character_)
  possibly_get_isbn13 <- possibly(get_isbn13, otherwise = NA_character_)
  possibly_get_publishers <- possibly(get_publishers, otherwise = NA_character_)
  possibly_get_date <- possibly(clean_date, otherwise = NA_character_)
  author <- possibly_get_authors(json)
  isbn_10 <- possibly_get_isbn10(json)
  isbn_13 <- possibly_get_isbn13(json)
  publisher <- possibly_get_publishers(json)


  df_part <- df_part |>
    mutate(
      author = author,
      isbn_10 = isbn_10,
      isbn_13 = isbn_13,
      publisher = publisher,
      details_publish_date = possibly_get_date(details_publish_date)
    )

  colnames(df_part) <- gsub("details_", "", colnames(df_part))

  df_part |>
    select(
      title,
      author,
      everything()
    )
}

#' @noRd
get_nested_field <- function(json, field) {
  json |>
    purrr::map(~ .x$details) |>
    purrr::map(~ .x[[field]]) |>
    purrr::map(
      ~ .x |>
        purrr::map_chr(~ .x[[1]])
    ) |>
    purrr::map_chr(~ paste(.x, collapse = ", "))
}

#' @noRd
get_authors <- function(json) {
  json |>
    purrr::map(~ .x$details) |>
    purrr::map(~ .x[["authors"]]) |>
    purrr::map(
      ~ .x |>
        purrr::map_chr(~ .x$name)
    ) |>
    purrr::map_chr(~ paste(.x, collapse = ", "))
}

#' @noRd
get_isbn10 <- function(json) {
  get_nested_field(json, "isbn_10")
}

#' @noRd
get_isbn13 <- function(json) {
  get_nested_field(json, "isbn_13")
}

#' @noRd
get_publishers <- function(json) {
  get_nested_field(json, "publishers")
}

#' @noRd
clean_date <- function(date) {
  regmatches(date, regexec("\\d{4,4}", date))[[1]]
}

#' Get the cover of a book from Open Library
#' @param root_api the base URL of the API
#' @param isbn_number the ISBN 10 number or the ISBN 13 number of the book
#' @param cover_size the size of the cover
#' @param resourcepath the path to the resource
#' @return a URL to the cover of the book
#' @importFrom glue glue
#' @importFrom utils download.file
#' @rdname fct_open_library
#' @export
#' @examples
#' get_cover(isbn_number = "9782365772013")
#' path <- "home/yohann/Documents/perso/mycomicslibrary/inst/app/www/cover_tmp/9782365772013.jpg"
get_cover <- function(
  root_api = "http://covers.openlibrary.org/b/isbn",
  isbn_number,
  cover_size = "M",
  resourcepath = resourcePaths()["covers"]
) {
  match.arg(cover_size, c("S", "M", "L"))
  url <- glue("{root_api}/{isbn_number}-{cover_size}.jpg")
  cover_output <- file.path(
    resourcepath,
    paste0(isbn_number, ".jpg")
  )

  if (!file.exists(cover_output)) {
    cover_dl <- try(
      download.file(
        url = url,
        cover_output,
        mode = "wb"
      ),
      silent = TRUE
    )

    if (inherits(cover_dl, "try-error")) {
      cover_output <- file.path(
        resourcepath,
        "image-not-found.jpg"
      )
    }
  }
  return(
    cover_output
  )
}

#' Return a random ISBN from mycomicslibrary::isbn_sample
#' @return a random ISBN
#' @rdname fct_open_library
#' @export
#' @examples
#' give_me_one_random_isbn()
give_me_one_random_isbn <- function() {
  mycomicslibrary::isbn_sample |>
    sample(1) |>
    as.character()
}
