# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' Prepare comics database to see collection
#' @return a comics database with only the columns needed to see the collection
#' @rdname fct_mod_130
#' @importFrom dplyr select mutate
#' @export
prepare_comics_db_to_see_collection <- function(comics_db, ns) {
  db <- comics_db |>
    select(
      titre,
      date_publication,
      nb_pages,
      editeur,
      possede,
      note,
      type_publication,
      statut,
      lien_cover,
      ISBN
    )

  validate_buttons <- sapply(seq_len(nrow(db)), function(i) {
    sprintf(
      '<button type="button" class="btn btn-primary" id="%s" onclick="%s">Enregistrer</button>',
      ns(paste0("button", i)),
      sprintf(
        "Shiny.setInputValue(
        '%s',
        '%s',
        {priority : 'event'}
      );
      Shiny.setInputValue(
        '%s',
        Math.random(),
        {priority : 'event'}
      );",
        ns("button_clicked_id"),
        ns(paste0("button", i)),
        ns("button_clicked")
      )
    )
  })

  # implémenter des selectInput pour les statuts

  db$validate <- validate_buttons

  db
}
