# WARNING - Generated by {fusen} from dev/flat_mod300_400.Rmd: do not edit by hand

#' Title
#'
#' Description
#'
#' @return
#' @rdname fct_mod300_400
#' @noRd
#' @export
show_hide_ids_depending_on_db_size <- function(db, table_id, nobook_id) {
  if (
    !isTruthy(db) ||
      nrow(db) == 0
  ) {
    golem::invoke_js(
      "showid",
      nobook_id
    )
    golem::invoke_js(
      "hideid",
      table_id
    )
  } else {
    golem::invoke_js(
      "hideid",
      nobook_id
    )
    golem::invoke_js(
      "showid",
      table_id
    )
  }
}
