# WARNING - Generated by {fusen} from dev/flat_mod500.Rmd: do not edit by hand

#' @noRd
#' @rdname fct_mod500
get_var_to_display_on_chartjs <- function() {
  list(
    "Publication year" = "annee_publication",
    "Rating" = "note",
    "Book condition" = "statut",
    "Type of book" = "type_publication"
  )
}
