# WARNING - Generated by {fusen} from dev/flat_database.Rmd: do not edit by hand

#' Connection
#'
#' @noRd
#' @rdname fct_comics_db
#' @examples
#' connect_to_comics_db()
connect_to_comics_db <- function() {
  DBI::dbConnect(
    RSQLite::SQLite(),
    get_database_path()
  )
}

#' get_database_path
#'
#' @noRd
#' @rdname fct_comics_db
#' @examples
#' get_database_path()
get_database_path <- function() {
  Sys.getenv(
    "COMICS_SQL_PATH",
    unset = file.path(system.file(package = "mycomicslibrary"), "db", "comics_db.sqlite")
  )
}

#' Comics db functions
#'
#' @rdname fct_comics_db
#' @noRd
#' @examples
#' withr::with_tempdir({
#'   withr::with_envvar(
#'     c("COMICS_SQL_PATH" = "BOBI.sqlite"),
#'     {
#'       init_comics_db()
#'       read_comics_db()
#'       append_feedback_db(
#'         ISBN = "1234567890",
#'         titre = "BOBI",
#'         possede = 1,
#'         date_publication = "2020-01-01",
#'         nb_pages = 154,
#'         note = 5,
#'         type_publication = "comics",
#'         statut = "Lu",
#'         lien_cover = "https://mycover.com"
#'       )
#'       read_comics_db()
#'       delete_feedback_db()
#'       unlink("BOBI.sqlite")
#'     }
#'   )
#' })

init_comics_db <- function() {
  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  if (!"comics" %in% DBI::dbListTables(con)) {
    DBI::dbCreateTable(
      con,
      "comics",
      fields = c(
        id_db = "TEXT",
        id_document = "TEXT",
        ISBN = "TEXT",
        possede = "INTEGER",
        titre = "TEXT",
        date_publication = "TEXT",
        nb_pages = "INTEGER",
        note = "INTEGER",
        type_publication = "TEXT",
        statut = "TEXT",
        lien_cover = "TEXT",
        datetime = "TEXT"
      )
    )
  }

  read_comics_db()
}


#' @rdname fct_comics_db

read_comics_db <- function() {
  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  DBI::dbReadTable(con, "comics")
}
#' @rdname fct_comics_db

append_feedback_db <- function(
  ISBN,
  titre,
  possede,
  date_publication,
  nb_pages,
  note,
  type_publication,
  statut,
  lien_cover
) {
  datetime <- Sys.time()

  id_db <- digest::digest(
    c(
      ISBN,
      titre,
      possede,
      date_publication,
      nb_pages,
      note,
      type_publication,
      statut,
      lien_cover,
      datetime
    )
  )
  id_document <- paste0(
    "doc_",
    digest::digest(ISBN)
  )

  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  DBI::dbAppendTable(
    con,
    "comics",
    data.frame(
      id_db = id_db,
      id_document = id_document,
      ISBN = ISBN,
      titre = titre,
      possede = possede,
      date_publication = date_publication,
      nb_pages = nb_pages,
      note = note,
      type_publication = type_publication,
      statut = statut,
      lien_cover = lien_cover,
      datetime = datetime
    )
  )
}
#' @rdname fct_comics_db

delete_feedback_db <- function() {
  con <- connect_to_comics_db()
  on.exit({
    DBI::dbDisconnect(con)
  })
  DBI::dbRemoveTable(
    con,
    "comics"
  )
}
