# WARNING - Generated by {fusen} from dev/flat_mod120.Rmd: do not edit by hand

#' @noRd
#' @param detected_isbn_value The detected ISBN value
#' @param ns The namespace
#' @importFrom shinyalert shinyalert
#' @importFrom shiny tags tagAppendChild
#' @rdname fct_mod_120
#' @examples
#' shiny_alert_isbn_detected_on_img()
shiny_alert_isbn_detected_on_img <- function(
  detected_isbn_value,
  ns
) {
  #  voir gestion des ns
  shinyalert(
    html = TRUE,
    title = "ISBN détecté !",
    type = "success",
    showCancelButton = TRUE,
    confirmButtonText = "Ajouter l'ISBN au champ de texte",
    cancelButtonText = "Abandonner",
    callbackJS = sprintf(
      "function(x) {
        //if (x !== false) {
               Shiny.setInputValue('%s', x, {priority: 'event'});
               //}
               }",
      ns("add_detected_isbn_to_textInput")
    ),
    text = tagList(
      tags$div(
        style = "
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;",
        tags$h5(
          sprintf("ISBN détecté : %s", detected_isbn_value)
        )
      )
    )
  )
}

#' @noRd
#' @rdname fct_mod_120
#' @importFrom shinyalert shinyalert
#' @importFrom shiny tags
#' @examples
#' shiny_alert_isbn_not_detected_on_img()
shiny_alert_isbn_not_detected_on_img <- function() {

}
