# WARNING - Generated by {fusen} from dev/flat_mod110.Rmd: do not edit by hand

#' A function to create the HTML for the modal API search result
#' @param book A list with the book information
#' @param book_cover A character with the URL of the book cover
#' @return A shiny.tag.list
#' @rdname fct_mod_110
#' @export
create_html_for_modal_api_search_result <- function(
  book,
  book_cover
) {
  tagList(
    tags$div(
      style = "
          display: flex;
          flex-direction: column;
          ",
      tags$div(
        tags$ul(
          style = "text-align: left; list-style-type: none;",
          tags$li(
            sprintf("Titre : %s", book$title)
          ),
          tags$li(
            sprintf("Auteur(s) : %s", book$author)
          ),
          tags$li(
            sprintf("Année de publication : %s", book$publish_date)
          ),
          tags$li(
            sprintf("Nombre de pages : %s", book$number_of_pages)
          ),
          tags$li(
            sprintf("Editeur : %s", book$publisher)
          )
        )
      ),
      tags$div(
        tags$img(
          src = book_cover,
          style = "width: 30%; height: auto;"
        )
      )
    )
  )
}
