# WARNING - Generated by {fusen} from dev/flat_mod120.Rmd: do not edit by hand

#' @noRd
#' @param detected_isbn_value The detected ISBN value
#' @param validate_button_id The id of the validate button
#' @param cancel_button_id The id of the cancel button
#' @importFrom shinyalert shinyalert
#' @importFrom shiny tags tagAppendChild
#' @rdname fct_mod_120
#' @examples
#' shiny_alert_isbn_detected_on_img()
shiny_alert_isbn_detected_on_img <- function(
  detected_isbn_value,
  validate_button_id,
  cancel_button_id
) {
  shinyalert(
    html = TRUE,
    title = "ISBN détecté !",
    type = "success",
    showCancelButton = FALSE,
    showConfirmButton = FALSE,
    text = tagList(
      tags$div(
        style = "
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;",
        tags$h5(
          sprintf("ISBN détecté : %s", detected_isbn_value)
        ),
        tags$span(
          tags$button(
            id = validate_button_id,
            class = "btn btn-success",
            "Ajouter l'ISBN détecté au menu de recherche",
          ),
          tags$button(
            id = cancel_button_id,
            class = "btn btn-danger",
            style = "background-color: #d9534f; border-color: #d43f3a;",
            "Abandonner"
          )
        )
      )
    )
  )
}

#' @noRd
#' @param cancel_button_id The id of the cancel button
#' @importFrom shinyalert shinyalert
#' @importFrom shiny tags tagAppendChild
#' @rdname fct_mod_120
#' @examples
#' shiny_alert_isbn_not_detected_on_img()
shiny_alert_isbn_not_detected_on_img <- function(cancel_button_id) {
  shinyalert(
    html = TRUE,
    title = "ISBN non détecté !",
    type = "error",
    showCancelButton = FALSE,
    showConfirmButton = FALSE,
    text = tagList(
      tags$div(
        style = "
          display: flex;
          flex-direction: column;
          align-items: center;
          justify-content: center;",
        tags$h5(
          "Aucun ISBN n'a été détecté, réessayez ou entrez l'ISBN manuellement."
        ),
        tags$span(
          tags$button(
            id = cancel_button_id,
            class = "btn btn-danger",
            style = "background-color: #d9534f; border-color: #d43f3a;",
            "Abandonner"
          )
        )
      )
    )
  )
}
