# WARNING - Generated by {fusen} from dev/flat_open_library.Rmd: do not edit by hand

#' Return a random ISBN from mycomicslibrary::isbn_sample
#' @return a random ISBN
#' @export
#' @examples
#' give_me_one_random_isbn()
give_me_one_random_isbn <- function() {
  mycomicslibrary::isbn_sample |>
    sample(1) |>
    as.character()
}
