# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' Make stars rating div
#' @param id the id of the div
#' @param note a note between 0 and max_note
#' @param max_note the maximum note
#' @return a div with stars
#' @importFrom htmltools tags
#' @export
#' @examples
#' make_stars_rating_div(note = 1)
make_stars_rating_div <- function(
  id = "id",
  note,
  max_note = 5
) {
  stars_full <- stars_empty <- list()
  if (note != 0) {
    stars_full <- lapply(1:note, function(x) {
      tags$span(class = "fa fa-star checked")
    })
  }

  if (note != max_note) {
    stars_empty <- lapply(1:(max_note - note), function(x) {
      tags$span(class = "fa fa-star")
    })
  }

  tagList(
    c(stars_full, stars_empty)
  ) |> as.character()
}
