# WARNING - Generated by {fusen} from dev/flat_mod130.Rmd: do not edit by hand

#' prepare comics database to see wishlist
#' @param comics_db a comics database
#' @param ns the namespace
#' @return a comics database with only the columns needed to see the wishlist
#' @importFrom dplyr select
#' @export
prepare_comics_db_to_see_wishlist <- function(comics_db, ns) {
  db <- comics_db |>
    select(
      id_document,
      titre,
      annee_publication,
      nb_pages,
      auteur,
      editeur,
      note,
      type_publication,
      statut,
      lien_cover,
      ISBN
    )

  add_to_collection_buttons <- sapply(seq_len(nrow(db)), function(i) {
    sprintf(
      '<button type="button" class="btn btn-primary" id="%s" onclick="%s"><i class="fa-solid fa-plus"></i></button>',
      ns(paste0("add_book_to_collection_button", i)),
      sprintf(
        "Shiny.setInputValue(
        '%s',
        '%s',
        {priority : 'event'}
      );
      Shiny.setInputValue(
        '%s',
        Math.random(),
        {priority : 'event'}
      );",
        ns("document_to_add_to_collection_id"),
        db$id_document[i],
        ns("add_to_collection_button_clicked")
      )
    )
  })

  delete_book_buttons <- sapply(seq_len(nrow(db)), function(i) {
    sprintf(
      '<button type="button" class="btn btn-danger" id="%s" onclick="%s"><i class="fa fa-trash"></i></button>',
      ns(paste0("delete_book_button", i)),
      sprintf(
        "Shiny.setInputValue(
        '%s',
        '%s',
        {priority : 'event'}
      );
      Shiny.setInputValue(
        '%s',
        Math.random(),
        {priority : 'event'}
      );",
        ns("document_to_delete_id"),
        db$id_document[i],
        ns("delete_button_clicked")
      )
    )
  })

  db$add_to_collection_buttons <- add_to_collection_buttons
  db$delete_book_buttons <- delete_book_buttons


  db |>
    select(
      titre,
      annee_publication,
      nb_pages,
      auteur,
      editeur,
      lien_cover,
      ISBN,
      add_to_collection_buttons,
      delete_book_buttons
    )
}
